import localFont from "next/font/local";
import { Red_Hat_Display, Spectral } from 'next/font/google'
import "./globals.css";

const geistSans = localFont({
   src: "./fonts/GeistVF.woff",
   variable: "--font-geist-sans",
   weight: "100 900",
});
const geistMono = localFont({
   src: "./fonts/GeistMonoVF.woff",
   variable: "--font-geist-mono",
   weight: "100 900",
});
const redHatDisplay = Red_Hat_Display({
   variable: '--red-hat-display',
   subsets: ['latin'],
   display: 'swap',
   weight: ['300', '400', '500', '600', '700', '800', '900']
})
const spectral = Spectral({
   variable: '--font-spectral',
   subsets: ['latin'],
   display: 'swap',
   weight: ['300', '400', '500', '600', '700', '800']
})
export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body
            className={`${geistSans.variable} ${geistMono.variable} ${redHatDisplay.variable} ${spectral.variable} antialiased`}
         >
            {children}
         </body>
      </html>
   );
}
